# No 1

In [2]:
# Perkalian Matrix
# TTL   : 28 november 2004  
# No Hp : 082287920590

import numpy as np

A = np.array([[2,8],[1,1],[0,4]])
B = np.array([[9,2],[0,5],[9,0]])

kali = A * B
print(kali)

[[18 16]
 [ 0  5]
 [ 0  0]]


# No 2

In [3]:
# Pengurangan Matrix

import numpy as np

A = np.array([[2,8],[1,1],[0,4]])
B = np.array([[9,2],[0,5],[9,0]])

kurang = A - B
print(kurang)

[[-7  6]
 [ 1 -4]
 [-9  4]]


# No 3

In [4]:
# Transpose Matrix

import numpy as np

A = np.array([[2,8],[1,1],[0,4]])
B = np.array([[9,2],[0,5],[9,0]])

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

print(transpose_A)
print(transpose_B)

[[2 1 0]
 [8 1 4]]
[[9 0 9]
 [2 5 0]]


# No 4

In [7]:
# Nilai Invers

import numpy as np

A = np.array([[2,8],[1,1]])
B = np.array([[9,2],[0,5]])


invers_A = np.linalg.inv(A)
invers_B = np.linalg.inv(B)

print("\nInvers matrix A :")
print("\nInvers matrix B :")
print(invers_A)
print(invers_B)



Invers matrix A :

Invers matrix B :
[[-0.16666667  1.33333333]
 [ 0.16666667 -0.33333333]]
[[ 0.11111111 -0.04444444]
 [ 0.          0.2       ]]


# No 5

In [6]:
# Nilai Determinan

import numpy as np

A = np.array([[2,8],[1,1]])
B = np.array([[9,2],[0,5]])

determinant_A = np.linalg.det(A)
determinant_B = np.linalg.det(B)
print("Determinan dari matrix A:", determinant_A)
print("Determinan dari matrix B:", determinant_B)

Determinan dari matrix A: -6.0
Determinan dari matrix B: 44.99999999999999
